[package]
name = "aoc-20"
version = "0.1.0"
authors = ["Mislav Marković <mislav.markovic95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
