[package]
name = "aoc-19"
version = "0.1.0"
authors = ["Mislav Markovic <mislav.markovic95@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
superslice = "1.0.0"